### ISSUE TITLE
forced to use ssl when inputing domain

### ISSUE THREAD

**Issue by gth7754125** [Doraemoe/LANreader#202]
Please use auto trying mechanism rather than ssl-forced.
for example, i use surge-ponte yo redirect my domain to local area network. but this app force to chang my domain input to use https protocol.
Please add a button to help change http protocol or use another way.

**Comment by Doraemoe** [comment]
Apple does not allow non https connection in App outside of LAN since like iOS9 I think. It is possible to disable this requirement but I'd rather not do it.
