### ISSUE TITLE
某些时候tag会无法显示

### ISSUE THREAD

**Issue by Putarku** [Doraemoe/LANreader#204]
服务端已经有对应元数据的情况下，软件内的tag只剩下少数几个
![187877cbc93824e13e26fd4610f857c1](https://github.com/Doraemoe/LANreader/assets/66679443/f8cc9888-f162-40f3-8b52-6091995419f6)
![image](https://github.com/Doraemoe/LANreader/assets/66679443/f38b05be-8849-4be4-9a42-eb3f82f521fa)

**Comment by Doraemoe** [comment]
重启能否解决？退回上一页再点回来呢？

**Comment by Doraemoe** [comment]
嗯，这可能和App内状态管理有关。我在等依赖的一个包更新，之后应该会着手重写这部分的逻辑，但是可能还得一段时间。

**Comment by Doraemoe** [comment]
请尝试使用最新版是否还有同样的问题。

**Comment by Putarku** [comment]
> 请尝试使用最新版是否还有同样的问题。

tag现在是没问题了，但是搜索界面很卡，而且点击作品大概率会闪退。

**Comment by Doraemoe** [comment]
请问用的什么设备？搜索的关键字？另外请到 `设置->隐私与安全性->分析与改进->分析数据` 里搜索LANreader并提供最近的一个闪退报告。

**Comment by Putarku** [comment]
![LANreader-2024-05-11-222336](https://github.com/Doraemoe/LANreader/assets/66679443/8ae08820-2618-408f-ba42-e7e09672b9ad)
后缀改了下

**Comment by Doraemoe** [comment]
我并没有百度账号，请将文件内容复制到 https://gist.github.com/

**Comment by Putarku** [comment]
> 我并没有百度账号，请将文件内容复制到 https://gist.github.com/

<script src="https://gist.github.com/Putarku/dcd06b5784d65a0f2502535047c8369b.js"></script>

**Comment by Doraemoe** [comment]
尝试了半天没法复现, 死马当活马医了. 请尝试使用这个版本并将iOS升级到最新版17.4.1, SwiftUI 有很多奇怪的 Bug 必须更新系统才能修复。
[LANreader.ipa.zip](https://github.com/Doraemoe/LANreader/files/15286461/LANreader.ipa.zip)

**Comment by Putarku** [comment]
> 尝试了半天没法复现, 死马当活马医了. 请尝试使用这个版本并将iOS升级到最新版17.4.1, SwiftUI 有很多奇怪的 Bug 必须更新系统才能修复。 [LANreader.ipa.zip](https://github.com/Doraemoe/LANreader/files/15286461/LANreader.ipa.zip)

现在不会闪退了，不过在搜索结果界面点开的书籍，都会直接跳到最后一页，包括带new图标的书籍

**Comment by Doraemoe** [comment]
我手头的两个设备都没法复现这个问题，
请试试这个，先删除老版本，再安装。之后点开一个会自动跳到最后一页的书籍。之后进到设置页面里复制一下App日志到这里。
[LANreader.zip](https://github.com/Doraemoe/LANreader/files/15287979/LANreader.zip)
