### ISSUE TITLE
[feature request] add navigation key for external keyboard or joystick

### ISSUE THREAD

**Issue by krakerz** [Doraemoe/LANreader#224]
Currently it only support tapping AFAIK (ipad), is it possible to make arrow key from external source (bluetooth controller for example) to navigate the page? Currently its moving the page instead go to "next" or "prev" page

**Comment by Doraemoe** [comment]
[LANreader.zip](https://github.com/user-attachments/files/15836735/LANreader.zip)

Could you please try if this works?

**Comment by krakerz** [comment]
Many thanks, this works perfect 👍
